"""create orchestration runs

Revision ID: 3365cc216c07
Revises: 6af91f312478
Create Date: 2026-08-23 09:49:58.564347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3365cc216c07'
down_revision: Union[str, Sequence[str], None] = '6af91f312478'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orchestration_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_stage', sa.String(length=100), nullable=True),
    sa.Column('completed_stages', sa.JSON(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orchestration_runs_id'), 'orchestration_runs', ['id'], unique=False)
    op.create_index(op.f('ix_orchestration_runs_project_id'), 'orchestration_runs', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orchestration_runs_project_id'), table_name='orchestration_runs')
    op.drop_index(op.f('ix_orchestration_runs_id'), table_name='orchestration_runs')
    op.drop_table('orchestration_runs')
    # ### end Alembic commands ###
